spring.application.name=User-Auth-Service

server.port=8081

# ===== DATASOURCE =====
spring.datasource.url=jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=ROOT
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===== JWT =====
# Access token: 15 minutes
jwt.access-token.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7e8d8d3260fc680f36fd41c5e55
jwt.access-token.expiration=900000
# Refresh token: 7 days
jwt.refresh-token.expiration=604800000

# ===== LOGGING =====
logging.level.com.service.userauth=DEBUG
logging.level.org.springframework.security=INFO