server.port=5003

spring.datasource.url=jdbc:postgresql://localhost:5432/enrollment_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

course.catalog.base-url=http://localhost:8000

#Later, in Docker, this may become:
#
#course.catalog.base-url=http://course-catalog-service:8000