apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: mini-lms
spec:
  selector:
    app: auth-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: mini-lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: REPLACE_ME/auth-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: http
