apiVersion: v1
kind: Service
metadata:
  name: enrollment-service
  namespace: mini-lms
spec:
  selector:
    app: enrollment-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrollment-service
  namespace: mini-lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enrollment-service
  template:
    metadata:
      labels:
        app: enrollment-service
    spec:
      containers:
        - name: enrollment-service
          image: REPLACE_ME/enrollment-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
              name: http
