apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: mini-lms
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: mini-lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: REPLACE_ME/api-gateway:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
