services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  auth-service:
    build: ./services/User-Auth-Service
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      mysql-db:
        condition: service_healthy

  enrollment-postgres:
    image: postgres:16
    container_name: enrollment-postgres
    environment:
      POSTGRES_DB: enrollment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - enrollment_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d enrollment_db"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  enrollment-service:
    build: "./services/Enrollment & Progress Service"
    container_name: enrollment-service
    ports:
      - "8082:8082"
    depends_on:
      enrollment-postgres:
        condition: service_healthy

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - enrollment-service

  course-mongo:
    image: mongo:7
    container_name: course-mongo
    volumes:
      - course_mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  course-catalog-service:
    build: "./services/Course Catalog Service"
    container_name: course-catalog-service
    ports:
      - "8083:8083"
    environment:
      MONGO_URI: mongodb://course-mongo:27017
      DATABASE_NAME: course_catalog_db
      COURSE_COLLECTION: courses
    depends_on:
      course-mongo:
        condition: service_healthy
  
  
  notification-mysql:
    image: mysql:8.0
    container_name: notification-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notification_db
    volumes:
      - notification_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s


  notification-service:
    build: "./services/Notification Service"
    container_name: notification-service
    ports:
      - "8085:8085"
    environment:
      DATABASE_URL: mysql://root:root@notification-mysql:3306/notification_db
    depends_on:
      notification-mysql:
        condition: service_healthy
    command: >
      sh -c "
      echo 'Waiting for notification MySQL...' &&
      sleep 20 &&
      npx prisma db push &&
      npm run dev
      "

volumes:
  enrollment_postgres_data:
  course_mongo_data:
  notification_mysql_data: