apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrollment-service
  namespace: mini-learning-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enrollment-service
  template:
    metadata:
      labels:
        app: enrollment-service
    spec:
      containers:
      - name: enrollment-service
        image: senura2001/enrollment-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://enrollment-postgres:5432/enrollment_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "postgres"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: enrollment-service
  namespace: mini-learning-platform
spec:
  selector:
    app: enrollment-service
  ports:
  - port: 8082
    targetPort: 8082
